[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
edition = "2021"
name = "solana-cli-config"
description = "Blockchain, Rebuilt for Scale - Zilch"
version = "1.16.0"
repository = "https://github.com/cryptohariseldon/solana-custom"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-cli-config"

[dependencies]
dirs-next = "2.0.0"
lazy_static = "1.4.0"
serde = "1.0.152"
serde_derive = "1.0.103"
serde_yaml = "0.9.13"
solana-clap-utils = { path = "../clap-utils", version = "=1.16.0" }
solana-sdk = { path = "../sdk", version = "=1.16.0" }
url = "2.2.2"

[dev-dependencies]
anyhow = "1.0.58"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
